# Docker Compose Configuration
# Contributors:
# Priyanshu Patel: Led the development and integration of the end-to-end system. Integrated PostgreSQL for real-time persistence, and built the Docker-based orchestration system.

version: "3.8"

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
      - "9644:9644"

  postgres:
    platform: linux/amd64
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: anomalies
    ports:
      - "5432:5432"
